version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd bookproject
      - npm install

  build:
    commands:
      - echo "유닛 테스트 실행 (실패해도 CI 계속 진행)"
      - npm test || echo "Tests failed but pipeline continues"
